services:
  project-zomboid:
    container_name: project-zomboid-server
    image: danixu86/project-zomboid-dedicated-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8766-8767:8766-8767/udp"
      - "16261-16262:16261-16262/udp"
      - "27015-27015:27015-27015/udp"
      - "16262-16294:16262-16294/tcp"
      - "27015-27015:27015-27015/tcp"
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
